Algoritmo "semnome"


Var
   n1, n2 : real


Inicio
      escreva("Digite dois números: ")
      leia(n1)
      leia(n2)
      
      enquanto n1 <> n2 faca
               
               se n1 > n2 entao
                  escreval("DECRESCENTE!")
               senao
                  escreval("CRESCENTE")
               fimse
               
               escreva("Digite dois números: ")
               leia(n1)
               leia(n2)
               
      fimenquanto


Fimalgoritmo