Algoritmo "semnome"


Var
   d1, d2, d3, maior : real


Inicio
      escreva("Digite as três distâncias: ")
      leia(d1)
      leia(d2)
      leia(d3)
      
      se (d1 > d2) e (d1 > d3) entao
         maior <- d1
      senao
         se d2 > d3 entao
            maior <- d2
         senao
            maior <- d3
         fimse
      fimse
      
      escreva("Maior distância: ", maior:1:2)

Fimalgoritmo